/*
 * Copyright (c) 2020 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */
#pragma once

#define MS_LOG 0
#define MS_RESET 1

#define MS_TP_SENSITIVITY_INCR 10
#define MS_TP_SENSITIVITY_DECR 11

#define MS_TP_NEG_INERTIA_INCR 12
#define MS_TP_NEG_INERTIA_DECR 13

#define MS_TP_VALUE6_INCR 14
#define MS_TP_VALUE6_DECR 15

#define MS_TP_PTS_THRESHOLD_INCR 16
#define MS_TP_PTS_THRESHOLD_DECR 17

#define MS_TP_PRESS_TO_SELECT_ENABLE 18
#define MS_TP_PRESS_TO_SELECT_DISABLE 19

#define MS_TP_DRAG_HYSTERESIS_INCR 20
#define MS_TP_DRAG_HYSTERESIS_DECR 21
